;Drush Make API Version
api = 2
defaults[projects][subdir] = "contrib"

;Drupal Core Version
core = 7.x
projects[drupal][version] = 7.52

;Custom Profile
projects[himssprofile][type] = "profile"
projects[himssprofile][subdir] = ""
projects[himssprofile][download][type] = "git"
projects[himssprofile][download][url] = "git@github.com:HIMSS/himss_profile.git"

;Custom Themes
projects[himsstheme][type] = "theme"
projects[himsstheme][subdir] = ""
projects[himsstheme][download][type] = "git"
projects[himsstheme][download][url] = "git@github.com:HIMSS/himss_theme.git"

;Custom Modules
;Below is an example
;projects[{{modulename}}][type] = "module"
;projects[{{modulename}}][subdir] = "custom"
;projects[{{modulename}}][download][type] = "git"
;projects[{{modulename}}][download][url] = "git@github.com:HIMSS/himss_theme.git"
;HIMSS                                HIMSS Personify [personify]                                                          Enabled
;HIMSS                                Personify Data Service Integration [personify_ds]                                    Enabled
;HIMSS                                Personify IMS [personify_ims]                                                        Not installed
;HIMSS Enterprise                     HIMSS Enterprise Taxonomy [himss_taxonomy]                                           Enabled        7.x-1.0
;HIMSS Enterprise                     HIMSS Utility [himss_utility]

;Contributed Themes
projects[bootstrap][subdir] = ""
projects[bootstrap][type] = "theme"
projects[bootstrap][version] = "3.x-dev"

;Contributed Modules
;projects[addanother][version] = "2.2"
projects[acquia_connector] = "2.17"
projects[acquia_purge] = "1.3"
projects[admin_menu] = "3.0-rc5"
projects[admin_views] = "1.6"
projects[ajax_comments] = "1.2"
projects[auto_entitylabel] = "1.3"
projects[addressfield] = "1.2"
projects[apachesolr] = "1.8"
projects[apachesolr_views] = "1.1-beta1"
projects[better_exposed_filters] = "3.2"
projects[bigint] = "1.06"
projects[bundle_copy] = "1.1"
projects[bundle_copy_commerce] = "1.x-dev"
projects[block_class] = "2.3"
projects[captcha] = "1.3"
projects[ckeditor] = "1.17"
projects[ctools] = "1.12"
projects[context] = "3.7"
projects[date] = "2.9"
projects[devel] = "1.5"
projects[disablepwstrength] = "1.1"
projects[eck] = "2.0-rc8"
projects[elysia_cron] = "2.4"
projects[email_registration] = "1.3"
projects[entity] = "1.8"
projects[entityreference] = "1.2"
projects[expire] = "2.0-rc4"
projects[flag] = "3.9"
projects[features] = "2.10"
projects[field_collection] = "1.0-beta12"
projects[field_group] = "1.5"
projects[field_permissions] = "1.0"
projects[fast_404] = "1.5"
projects[fivestar] = "2.2"
projects[fontawesome] = "2.6"
projects[google_tag] = "1.0"
projects[helper] = "1.9"
projects[hierarchical_select] = "3.0-beta7"
projects[htmlmail] = "2.65"
projects[inline_entity_form] = "1.8"
projects[inline_conditions] = "1.0-alpha7"
projects[imagecache_external] = "2.1"
projects[imce] = "1.10"
projects[jcarousel] = "2.7"
projects[jquery_update] = "2.7"
projects[libraries] = "2.3"
projects[link] = "1.4"
projects[masquerade] = "1.0-rc7"
projects[memcache] = "1.5"
projects[menu_attributes] = "1.0"
projects[menu_block] = "2.7"
projects[module_filter] = "2.0"
projects[term_reference_tree] = "1.10"
projects[mailsystem] = "3.0-alpha1"
projects[mimemail] = "1.0-beta4"
projects[recaptcha] = "2.2"
projects[rules] = "2.9"
projects[pathauto] = "1.3"
projects[securepages] = "1.0-beta2"
projects[shs] = "1.6"
projects[strongarm] = "2.0"
projects[special_menu_items] = "2.0"
projects[taxonomy_manager] = "1.0"
projects[taxonomy_menu] = "1.5"
projects[taxonomy_menu_block] = "1.4"
projects[token] = "1.6"
projects[user_registrationpassword] = "1.4"
projects[variable] = "2.5"
projects[views] = "3.14"
projects[views_between_dates_filter] = "1.0"
projects[views_bulk_operations] = "3.3"
projects[views_content_cache] = "3.0-alpha3"
projects[views_data_export] = "3.1"
projects[votingapi] = "2.12"
projects[webform] = "4.14"
projects[xmlsitemap] = "2.3"
